package frlp.utn.edu.ar.domain.enumeration;

/**
 * The CategoriaSemantica enumeration.
 */
public enum CategoriaSemantica {
    SONIDOS, ANIMAL, VEHICULOS, ALIMENTACION, ROPA, CUERPO, JUGUETES, COCINA, MUEBLE_CUARTO, LUGAR_OBJETO, PERSONAS, RUTINAS_JUEGOS, ACCIONES_PROCESOS, TIEMPO, CUALIDADES_ATRIBUTOS, PRONOMBRES, PREGUNTAS, PREPOSICIONES_ARTICULOS, CUALIFICADORES_ADVERBIOS, LOCATIVOS
}
