export enum CategoriaSemantica {
  SONIDOS = 'SONIDOS',

  ANIMAL = 'ANIMAL',

  VEHICULOS = 'VEHICULOS',

  ALIMENTACION = 'ALIMENTACION',

  ROPA = 'ROPA',

  CUERPO = 'CUERPO',

  JUGUETES = 'JUGUETES',

  COCINA = 'COCINA',

  MUEBLE_CUARTO = 'MUEBLE_CUARTO',

  LUGAR_OBJETO = 'LUGAR_OBJETO',

  PERSONAS = 'PERSONAS',

  RUTINAS_JUEGOS = 'RUTINAS_JUEGOS',

  ACCIONES_PROCESOS = 'ACCIONES_PROCESOS',

  TIEMPO = 'TIEMPO',

  CUALIDADES_ATRIBUTOS = 'CUALIDADES_ATRIBUTOS',

  PRONOMBRES = 'PRONOMBRES',

  PREGUNTAS = 'PREGUNTAS',

  PREPOSICIONES_ARTICULOS = 'PREPOSICIONES_ARTICULOS',

  CUALIFICADORES_ADVERBIOS = 'CUALIFICADORES_ADVERBIOS',

  LOCATIVOS = 'LOCATIVOS',
}
